site_name: Hacktoberfest Korea
copyright: This is korean fan page of Hacktoberfest
site_url: 'https://www.hacktoberfestkorea.com/'

theme:
  name: material
  language: kr
  custom_dir: 'theme'
  palette:
    scheme: default
    primary: deep purple
  favicon: assets/favicon.png

nav:
  - Home: index.md
  - 초보자용 가이드: beginners_guide.md

markdown_extensions:
  - attr_list
